version: "3.5"
services:
  app:
    image: hcr.io/rcosdp/cs-sapporo-service:latest
    container_name: sapporo-service
    volumes:
      # The ones below are mounted for cwltool and DinD.
      - ${PWD}/run:${PWD}/run
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      # Priority: [Command Line Argument] -> [Environment Variable] -> [Default Values]
      - SAPPORO_HOST=0.0.0.0
      - SAPPORO_PORT=1122
      - SAPPORO_DEBUG=False
      - SAPPORO_RUN_DIR=${PWD}/run
      # - SAPPORO_DATA_REMOVE_OLDER_THAN_DAYS=30
      # - SAPPORO_GET_RUNS=False
      # - SAPPORO_RUN_ONLY_REGISTERED_WORKFLOWS=False
      # - SAPPORO_ACCESS_CONTROL_ALLOW_ORIGIN=*
      # - SAPPORO_URL_PREFIX=/
    ports:
      - 127.0.0.1:1122:1122
    restart: on-failure
    working_dir: /app
    command: [ "sapporo" ]
    networks:
      - sapporo

networks:
  sapporo:
    name: sapporo-network
